app:
  name: "web_app"
  mode: "dev"
  port: 8080

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "172.30.198.210"
  port: 3306
  user: "root"
  password: "Mysql:12138"
  dbname: "sql_demo"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "172.30.198.210"
  port: 6379
  db: 0
  password: ""
  pool_size: 100
